# .goreleaser.yaml
before:
  hooks:
    - go mod tidy
    - go mod verify
builds:
  -
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.BuildUser=dorokhin_bot
      -X github.com/prometheus/common/version.Revision={{.Commit}}
      -X github.com/prometheus/common/version.Branch=main
      -X github.com/prometheus/common/version.BuildDate={{.Date}}
